spring:
  datasource:
    url: jdbc:mysql://localhost:3306/doex?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    #    url: jdbc:mysql://localhost:3306/site?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  security:
    oauth2:
      resource server:10
  sql:
    init:
      mode: never
      schema-locations: classpath:/db/migration/schema.sql
      data-locations: classpath:/db/migration/data.sql
jwt:
  secret: mySuperSecretKey
  expiration:
    minutes: 30
  refresh-threshold: 300  # 5 minutes
  issuer: myapp
  audience: backend-service
  algorithm: HS256

  header:
    type: Authorization
    prefix: Bearer
  token:
    prefix: JWT
